config/routes.rb
Comun::Application.routes.draw do
  resources :messages

  resources :clients

  resources :groups

  root :to => 'clients#index'

end

app/models/client.rb
#encoding: utf-8
class Client < ActiveRecord::Base
  attr_accessible :email, :name, :smsmail, :group_ids

  has_and_belongs_to_many :groups

  HUMANIZED_ATTRIBUTES = {
  	:email => "Электронный адрес",
  	:name => "Имя клиента",
  	:smsmail => "Сотовый телефон"
  }
  def self.human_attribute_name(attr, options={})
	HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  validates :name, 	:presence => true,
  					:length   => { :maximum => 250 }

 email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 
 validates :email, :presence => {:message => "не указан."},
  						:format   => { :with => email_regex, :message => "не соответствует формату." },
                  :allow_nil => true, :if => :email?


  smsmail_regex = /^7[0-9]{10}$/i
  validates :smsmail,  	:presence => {:message => "не указан."},
  						:format   => { :with => smsmail_regex, :message => "не соответствует формату 79991112233." },
                  :allow_nil => true, :if => :smsmail?
end

app/models/clients_groups.rb
class ClientsGroups < ActiveRecord::Base
  belongs_to :client
  belongs_to :group
  # attr_accessible :title, :body
end

app/models/group.rb
#encoding: utf-8
class Group < ActiveRecord::Base
  attr_accessible :name, :client_ids

  has_and_belongs_to_many :clients

  HUMANIZED_ATTRIBUTES = {
  	:name => "Наименование"
  }
  def self.human_attribute_name(attr, options={})
	HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  validates :name, 	:presence => true,
  					:length   => { :maximum => 250 }


end

app/models/message.rb
#encoding: utf-8
require 'net/http'
class Message < ActiveRecord::Base
  belongs_to :client
  attr_accessible :text, :client_id

  HUMANIZED_ATTRIBUTES = {
  	:client => "Имя клиента",
  	:client_id => "Имя клиента",
  	:text => "Текст сообщения"
  }
  def self.human_attribute_name(attr, options={})
	HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  after_save :sms

  def Send( smsmail, smstext )
	uri = URI('http://api.smsfeedback.ru/send')
	            params = { :login => 'mgerasim', :password => 'zaq12wsx', :phone => smsmail, :text => text, :sender => 'MCPIR.RU'}
	            uri.query = URI.encode_www_form(params)
	 
	 
	        res = Net::HTTP.get_response(uri)
	            puts res.body if res.is_a?(Net::HTTPSuccess)

	end

	def sms
	Send(client.smsmail, text)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :smsmail %><br />
    <%= f.text_field :smsmail %>
  </div>
  <h2>Группы:</h2>
  <% if Group.count != 0 %>
      <% for group in Group.find(:all) %>
        <div>
        <%= check_box_tag "client[group_ids][]", group.id, @client.groups.include?(group)%>
        <%= group.name%>
        </div>
      <% end %>
  <% else %>
      <p>Создайте первую группу</p>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/_groups.html.erb
<h5>Принадлежность к группам:</h5>
<% @client.groups.each do |group| %>
  
    <div><%= group.name %></div>
  
<% end %>

app/views/clients/edit.html.erb
<h1>Редактирование</h1>

<%= render 'form' %>

<%= link_to 'Показать', @client %> |
<%= link_to 'Назад', clients_path %>

app/views/clients/index.html.erb
<h1>Список клиентов</h1>

<table>
  <tr>
    <th><%= Client.human_attribute_name(:name) %></th>
    <th><%= Client.human_attribute_name(:email) %></th>
    <th><%= Client.human_attribute_name(:smsmail) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.email %></td>
    <td><%= client.smsmail %></td>
    <td><%= link_to 'Показать', client %></td>
    <td><%= link_to 'Редактировать', edit_client_path(client) %></td>
    <td><%# link_to 'Удалить', client, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить', new_client_path %>

app/views/clients/new.html.erb
<h1>Новый клиент</h1>

<%= render 'form' %>

<%= link_to 'Назад', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= Client.human_attribute_name(:name) %>:</b>
  <%= @client.name %>
</p>

<p>
  <b><%= Client.human_attribute_name(:email) %>:</b>
  <%= @client.email %>
</p>

<p>
  <b><%= Client.human_attribute_name(:smsmail) %>:</b>
  <%= @client.smsmail %>
</p>

<%= render 'groups' %>

<%= link_to 'Редактировать', edit_client_path(@client) %> |
<%= link_to 'Назад', clients_path %>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Редактирование группы</h1>

<%= render 'form' %>

<%= link_to 'Показать', @group %> |
<%= link_to 'Назад', groups_path %>

app/views/groups/index.html.erb
<h1>Список групп</h1>

<table>
  <tr>
    <th><%= Group.human_attribute_name(:name) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= link_to 'Показать', group %></td>
    <td><%= link_to 'Редактировать', edit_group_path(group) %></td>
    <td><%# link_to 'Удалить', group, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить', new_group_path %>

app/views/groups/new.html.erb
<h1>Новая группа</h1>

<%= render 'form' %>

<%= link_to 'Назад', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= Group.human_attribute_name(:name) %>:</b>
  <%= @group.name %>
</p>


<%= link_to 'Редактировать', edit_group_path(@group) %> |
<%= link_to 'Назад', groups_path %>

app/views/layouts/_menu.html.erb
<%= link_to "Клиенты", 						clients_path %> |
<%= link_to "Группы", 							groups_path%> |
<%= link_to "Сообщения", 							messages_path%> |
<%= link_to "Отправить сообщение", :controller => :messages, :action => :new %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Сервис рассылок</title>
  
  <!-- Framework CSS -->
  <link rel="stylesheet" href="blueprint/screen.css" type="text/css" media="screen, projection" />
  <link rel="stylesheet" href="blueprint/print.css" type="text/css" media="print" />
  <!--[if IE]><link rel="stylesheet" href="blueprint/ie.css" type="text/css" media="screen, 	projection" /><![endif]-->

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	

		<%= render 'layouts/menu' %>
		<%= yield %>

</div>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if Client.where("smsmail <> ''").count != 0 %>
      <div class="field">
        <%= f.label :client %><br />
        <%= f.select :client_id, Client.where("smsmail <> ''").map { |u| [u.name + ' <' + u.smsmail + '>' , u.id] } %>
      </div>
      <div class="field">
        <%= f.label :text %><br />
        <%= f.text_area :text %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% else %>
      Создайте клиента с сотовым телефоном!
  <% end %>
<% end %>

app/views/messages/edit.html.erb
<h1>Редактирование сообщения</h1>

<%= render 'form' %>

<%= link_to 'Показать', @message %> |
<%= link_to 'Назад', messages_path %>

app/views/messages/index.html.erb
<h1>Список сообщений</h1>

<table>
  <tr>
    <th>Клиент</th>
    <th>Текст</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.client.name %></td>
    <td><%= message.text %></td>
    <td><%# link_to 'Показать', message %></td>
    <td><%# link_to 'Редактировать', edit_message_path(message) %></td>
    <td><%# link_to 'Удалить', message, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить', new_message_path %>

app/views/messages/new.html.erb
<h1>Новое сообщение</h1>

<%= render 'form' %>

<%= link_to 'Назад', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client:</b>
  <%= @message.client.name %>
</p>

<p>
  <b>Text:</b>
  <%= @message.text %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>